depscan/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url('', include('mainapp.urls')),
]

mainapp/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^home$', views.home, name="home"),
    url(r'^in_progress$', views.in_progress, name="in_progress"),
    url(r'^in_progress_id/(\d+)$', views.in_progress, name="in_progress_id"),
    url(r'^restart_scan/(\d+)$', views.restart_scan, name="restart_scan"),
    url(r'^delete_scan/(\d+)$', views.delete_scan, name="delete_scan"),
    url(r'^history$', views.history, name="history"),
    url(r'^scan_report/(\d+)$', views.scan_report, name="scan_report"),
    url(r'^dependency/(\d+)$', views.dependency, name="dependency"),
    url(r'^autoscan/start/(\d+)$', views.enable_autoscan, name="enable_auto_scan"),
    url(r'^autoscan/stop/(\d+)$', views.disable_autoscan, name="disable_auto_scan"),
    url(r'^cve/(\d+)$', views.cve, name="cve"),
    url(r'', views.home),
]

mainapp/models/cve.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from mainapp.models.scan import Scan, Dependency, Cpe

class Cve(models.Model):
    # Attributes
    identifier = models.CharField(max_length=256, null=True)
    cwe = models.CharField(max_length=256, null=True)
    published = models.CharField(max_length=512, null=True)
    cvss_time = models.CharField(max_length=512, null=True)
    cvss = models.CharField(max_length=512, null=True)
    modified = models.CharField(max_length=512, null=True)
    last_modified = models.CharField(max_length=512, null=True)
    access_authentication = models.CharField(max_length=512, null=True)
    access_complexity = models.CharField(max_length=512, null=True)
    access_vector = models.CharField(max_length=512, null=True)
    availability = models.CharField(max_length=512, null=True)
    confidentiality = models.CharField(max_length=512, null=True)
    integrity = models.CharField(max_length=512, null=True)
    summary = models.TextField(null=True)
    # Relationship
    scan = models.ForeignKey(Scan, on_delete=models.CASCADE, null=True)
    dependency = models.ForeignKey(Dependency, on_delete=models.CASCADE, null=True)
    cpe = models.ForeignKey(Cpe, on_delete=models.CASCADE, null=True)

class CveVulnerableConfiguration(models.Model):
    # Attributes
    identifier = models.CharField(max_length=512, null=True)
    title = models.CharField(max_length=512, null=True)
    # Relationship
    cve = models.ForeignKey("CVE", on_delete=models.CASCADE, null=True)

class CveReference(models.Model):
    # Attributes
    url = models.CharField(max_length=512, null=True)
    # Relationship
    cve = models.ForeignKey("CVE", on_delete=models.CASCADE, null=True)

class CveNessus(models.Model):
    # Attributes
    nasl_family = models.CharField(max_length=256, null=True)
    nasl_id = models.CharField(max_length=256, null=True)
    description = models.TextField(max_length=2048, null=True)
    last_seen = models.CharField(max_length=256, null=True)
    modified = models.CharField(max_length=256, null=True)
    plugin_id = models.CharField(max_length=256, null=True)
    published = models.CharField(max_length=256, null=True)
    reporter = models.CharField(max_length=256, null=True)
    source = models.CharField(max_length=256, null=True)
    title = models.CharField(max_length=256, null=True)
    # Relationship
    cve = models.ForeignKey("CVE", on_delete=models.CASCADE, null=True)

mainapp/models/exploitdb.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from mainapp.models.scan import Scan, Dependency

class ExploitDb(models.Model):
    # Attributes
    title = models.TextField(null=True)
    edb_id = models.CharField(max_length=256, null=True)
    date = models.CharField(max_length=256, null=True)
    author = models.CharField(max_length=256, null=True)
    exploit_type = models.CharField(max_length=256, null=True)
    platform = models.CharField(max_length=256, null=True)
    url = models.CharField(max_length=512, null=True)
    # Relationships
    scan = models.ForeignKey(Scan, on_delete=models.CASCADE, null=True)
    dependency = models.ForeignKey(Dependency, on_delete=models.CASCADE, null=True)

mainapp/models/scan.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Scan(models.Model):
    # Attributes
    name = models.CharField(max_length=512, null=True)
    random_id = models.CharField(max_length=512, null=True)
    repository = models.CharField(max_length=512, null=True)
    language = models.CharField(max_length=512, null=True)
    state = models.CharField(max_length=512, null=True)
    date = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    last_scan = models.DateTimeField(auto_now_add=False, auto_now=False, null=True)
    next_scan = models.DateTimeField(auto_now_add=False, auto_now=False, null=True)

    def get_repo_directory(self):
        """ Returns the directory in which the repo will be / is cloned. """
        return "mainapp/static/repos/"+str(self.random_id)
    
    def has_vulns(self):
        """ Returns True if a vulneranility was found for this project """
        has_vulns = False
        # Check each dependency
        for dep in self.dependency_set.all():
            if has_vulns:
                continue
            if (len(dep.cve_set.all()) > 0 or len(dep.exploitdb_set.all()) > 0):
                has_vulns = True
        return has_vulns
    
    def tot_cve(self):
        """ Returns the total number of CVEs found """
        tot_cve = 0
        for dep in self.dependency_set.all():
            tot_cve += len(dep.cve_set.all())
        return tot_cve
    
    def tot_exploit(self):
        """ Return the total number of exploits found """
        tot_exploit = 0
        for dep in self.dependency_set.all():
            tot_exploit += len(dep.exploitdb_set.all())
        return tot_exploit

class ScanTask(models.Model):
    # Attributes
    name = models.CharField(max_length=512, null=True)
    state = models.CharField(max_length=512, null=True)
    date = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
    # Relationship
    scan = models.ForeignKey("Scan", on_delete=models.CASCADE, null=True)

    def new_task(self, scan, name):
        self.state = "in_progress"
        self.name = name
        self.scan = scan
        self.save()
        return
    
    def task_done(self):
        self.state = "done"
        self.save()
        return

class Dependency(models.Model):
    # Attributes
    name = models.CharField(max_length=512, null=True)
    version = models.CharField(max_length=512, null=True)
    upstream_version = models.CharField(max_length=512, null=True)
    # Relationships
    scan = models.ForeignKey("Scan", on_delete=models.CASCADE, null=True)
    parent_dep = models.ForeignKey("Dependency", on_delete=models.CASCADE, null=True)

    def has_vulns(self):
        return (len(self.cve_set.all()) > 0 or len(self.exploitdb_set.all()) > 0)

class Cpe(models.Model):
    # Attributes
    part = models.CharField(max_length=512, null=True)
    vendor = models.CharField(max_length=512, null=True)
    product = models.CharField(max_length=512, null=True)
    version = models.CharField(max_length=512, null=True)
    dep = models.ForeignKey("Dependency", on_delete=models.CASCADE, null=True)

    def cpe_string(self):
        return ":".join(["cpe:2.3", self.part, self.vendor, self.product, self.version])

mainapp/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from mainapp.models.exploitdb import ExploitDb

class ScanForm(forms.Form):
    name = forms.CharField(max_length=512)
    repo_link = forms.CharField(max_length=512)

mainapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.core.exceptions import ObjectDoesNotExist
from background_task.models import Task

from mainapp.forms import ScanForm
from mainapp.models.scan import Scan, Dependency
from mainapp.models.cve import Cve
from mainapp.tools.tasks import scan_init, delete_repo

from shutil import rmtree
from os import path

def home(request):
    """ Home page - Scan creation """
    # If request is a post request, check user input
    if request.method == "POST":
        # Check input
        form = ScanForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            repo_link = form.cleaned_data['repo_link']
            # Create new Scan
            scan = Scan()
            scan.name = name
            scan.repository = repo_link
            scan.state = "in_progress"
            scan.random_id = get_random_string(length=12)
            # Midnight today
            midnight_today = timezone.datetime(timezone.now().year, timezone.now().month, timezone.now().day)
            scan.next_scan = midnight_today + timezone.timedelta(days=1)
            scan.save()
            # Schedule background task every day at midnight
            scan_init(scan.id, repeat=86400, schedule=midnight_today)
            # Redirect to in_progress page
            return redirect("in_progress_id", scan.id)

    return render(request, "mainapp/home.html")

def in_progress(request, scan_id=0):
    """ Display scans that are currently in progress """
    scans_in_progress = []
    if scan_id == 0:
        scans_in_progress = Scan.objects.filter(state="in_progress")
    else:
        scan = Scan.objects.get(pk=scan_id)
        if scan.state == "done" or scan.state == "error":
            return redirect("scan_report", scan.id)
        scans_in_progress = [scan]
    
    return render(request, 'mainapp/in_progress.html', {"scans": scans_in_progress})

def restart_scan(request, scan_id):
    """ Execute a dependency scan now """
    try:
        scan = Scan.objects.get(pk=scan_id)
    except ObjectDoesNotExist:
        return HttpResponse(status=500)
    scan.state = "in_progress"
    scan.dependency_set.all().delete()
    scan.scantask_set.all().delete()
    scan.save()
    # Reschedule a dependency scan
    scan_init(scan_id)
    # Redirect to in_progress page
    return redirect("in_progress_id", scan.id)

def enable_autoscan(request, scan_id):
    """ Restart a scan every day at midnight """
    try:
        scan = Scan.objects.get(pk=scan_id)
    except ObjectDoesNotExist:
        return HttpResponse(status=500)
    # Delete all previous autoscan
    Task.objects.filter(task_name="mainapp.tools.tasks.scan_init",
                        task_params="[["+str(scan.id)+"], {}]",
                        repeat=86400).delete()
    # Midnight tomorrow
    midnight_tomorrow = timezone.datetime(timezone.now().year, timezone.now().month, timezone.now().day) + timezone.timedelta(days=1)
    # Reschedule a scan for midnight tomorrow
    scan_init(scan.id, repeat=86400, schedule=midnight_tomorrow)
    scan.next_scan = midnight_tomorrow
    scan.save()
    return redirect('scan_report', scan.id)

def disable_autoscan(request, scan_id):
    """ Disable scan auto-rescheduling """
    try:
        scan = Scan.objects.get(pk=scan_id)
    except ObjectDoesNotExist:
        return HttpResponse(status=500)
    Task.objects.filter(task_name="mainapp.tools.tasks.scan_init",
                        task_params="[["+str(scan.id)+"], {}]",
                        repeat=86400).delete()
    # Update user config
    scan.next_scan = None
    scan.save()
    return redirect('scan_report', scan.id)

def delete_scan(request, scan_id):
    """ Delete a scan and stop any dependency scan """
    try:
        scan = Scan.objects.get(pk=scan_id)
    except ObjectDoesNotExist:
        return HttpResponse(status=500)
    # Delete background_task
    bg_task = Task.objects.filter(task_params="[["+str(scan.id)+"], {}]").delete()
    # Delete repository folder
    delete_repo(scan.get_repo_directory())
    # Delete scan
    scan.dependency_set.all().delete()
    scan.scantask_set.all().delete()
    scan.delete()
    # Redirect to in_progress page
    return redirect("home")

def history(request):
    # Select all scans
    scans = Scan.objects.all()
    return render(request, 'mainapp/history.html', {"scans": scans})

def scan_report(request, scan_id):
    """ Show scan report """
    try:
        scan = Scan.objects.get(pk=scan_id)
        return render(request, 'mainapp/scan_report.html', {"scan": scan})
    except ObjectDoesNotExist:
        return HttpResponse(status=404)

def dependency(request, dep_id):
    """ Show dependency report """
    try:
        dep = Dependency.objects.get(pk=dep_id)
        return render(request, 'mainapp/dependency.html', {'dep': dep})
    except ObjectDoesNotExist:
        return HttpResponse(status=404)

def cve(request, cve_id):
    """ Show CVE report """
    try:
        cve = Cve.objects.get(pk=cve_id)
        return render(request, 'mainapp/cve_report.html', {'cve': cve})
    except ObjectDoesNotExist:
        return HttpResponse(status=404)

mainapp/templates/mainapp/cve_report.html
{% extends "layout.html" %}
{% block body %}
<div class="container depscan-blue-text">
    <div class="row" style="margin-top: 2em; margin-bottom: 0; border-bottom: 2px solid #426ca0;">
        <h5>CVE report: {{ cve.identifier }}</h5>
    </div>
    <div class="row">
        <div class="col s12" style="margin: 1em 0">
            <a href="{% url 'dependency' cve.dependency.id %}" type="submit" class="waves-effect waves-light btn depscan-btn right">
                <i class="material-icons left">navigate_before</i>
                Back to dependency report
            </a>
        </div>
        <div class="col s12">
            <div class="depscan-card z-depth-1 col s12" style="margin-top: 1em; padding: 0;">
                <div class="col s12 depscan-card-title-wrapper">
                </div>
                <div class="col s12">
                    <div class="col s12" style="margin-bottom: 0;">
                        <h5>
                            <b>Info</b>
                        </h5>
                    </div>
                    <div class="col s12" style="margin-bottom: 2em;">
                        <table class="bordered">
                            <tbody>
                                <tr>
                                    <td>
                                        <b>CVE</b>
                                    </td>
                                    <td>{{ cve.identifier }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>CWE</b>
                                    </td>
                                    <td>{{ cve.cwe }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Published</b>
                                    </td>
                                    <td>{{ cve.published }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>CVSS</b>
                                    </td>
                                    <td>{{ cve.cvss }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Last modified</b>
                                    </td>
                                    <td>{{ cve.last_modified }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col s12" style="margin-bottom: 0;">
                        <h5>
                            <b>Summary</b>
                        </h5>
                    </div>
                    <div class="col s12">
                        <p>{{ cve.summary }}</p>
                    </div>
                    <div class="col s12" style="margin-bottom: 0;">
                        <h5>
                            <b>Access</b>
                        </h5>
                    </div>
                    <div class="col s12" style="margin-bottom: 2em;">
                        <table class="bordered">
                            <tbody>
                                <tr>
                                    <td>
                                        <b>Access authentication</b>
                                    </td>
                                    <td>{{ cve.access_authentication }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Access complexity</b>
                                    </td>
                                    <td>{{ cve.access_complexity }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Access vector</b>
                                    </td>
                                    <td>{{ cve.access_vector }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col s12" style="margin-bottom: 0;">
                        <h5>
                            <b>Impact</b>
                        </h5>
                    </div>
                    <div class="col s12" style="margin-bottom: 2em;">
                        <table class="bordered">
                            <tbody>
                                <tr>
                                    <td>
                                        <b>Integrity</b>
                                    </td>
                                    <td>{{ cve.integrity }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Availability</b>
                                    </td>
                                    <td>{{ cve.availability }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Confidentiality</b>
                                    </td>
                                    <td>{{ cve.confidentiality }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col s12">
            <div class="depscan-card z-depth-1 col s12" style="margin-top: 1em; padding: 0;">
                <div class="col s12 depscan-card-title-wrapper">
                </div>
                <div class="col s12">
                    <div class="col s12" style="margin-bottom: 0;">
                        <h5>
                            <b>References</b>
                        </h5>
                    </div>
                    <div class="col s12" style="margin-bottom: 2em;">
                        <table class="bordered highlight">
                            <thead>
                                <tr>
                                    <th>Url</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ref in cve.cvereference_set.all %}
                                <tr>
                                    <td><a href="{{ ref.url }}" target="_blank">{{ ref.url }}</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col s12">
            <div class="depscan-card z-depth-1 col s12" style="margin-top: 1em; padding: 0;">
                <div class="col s12 depscan-card-title-wrapper">
                </div>
                <div class="col s12">
                    <div class="col s12" style="margin-bottom: 0;">
                        <h5>
                            <b>Nessus plugin</b>
                        </h5>
                    </div>
                    {% for nessus in cve.cvenessus_set.all %}
                    <div class="col s12" style="margin-bottom: 2em;">
                        <h5>
                            <b>Info</b>
                        </h5>
                        <table class="bordered">
                            <tbody>
                                <tr>
                                    <td>
                                        <b>NASL family</b>
                                    </td>
                                    <td>{{ nessus.nasl_family }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>NASL id</b>
                                    </td>
                                    <td>{{ nessus.nasl_id }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Title</b>
                                    </td>
                                    <td>{{ nessus.title }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Reporter</b>
                                    </td>
                                    <td>{{ nessus.reporter }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Plugin ID</b>
                                    </td>
                                    <td>{{ nessus.plugin_id }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Last seen</b>
                                    </td>
                                    <td>{{ nessus.last_seen }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Modified</b>
                                    </td>
                                    <td>{{ nessus.modified }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Published</b>
                                    </td>
                                    <td>{{ nessus.published }}</td>
                                </tr>
                                <tr>
                                    <td>
                                        <b>Source</b>
                                    </td>
                                    <td><a href="{{ nessus.source }}" target="_blank">{{ nessus.source }}</a></td>
                                </tr>
                            </tbody>
                        </table>
                        <h5>
                            <b>Description</b>
                        </h5>
                        <p>{{ nessus.description }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col s12">
            <div class="depscan-card z-depth-1 col s12" style="margin-top: 1em; padding: 0;">
                <div class="col s12 depscan-card-title-wrapper">
                </div>
                <div class="col s12">
                    <div class="col s12" style="margin-bottom: 0;">
                        <h5>
                            <b>Vulnerable configurations</b>
                        </h5>
                    </div>
                    <div class="col s12" style="margin-bottom: 2em;">
                        <table class="bordered highlight">
                            <tbody>
                                {% for conf in cve.cvevulnerableconfiguration_set.all %}
                                <tr>
                                    <td>{{ conf.title }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/home.html
{% extends "layout.html" %}
{% block body %}
<div class="container depscan-blue-text">
    <div class="row" style="margin-top: 2em; margin-bottom: 0; border-bottom: 2px solid #426ca0;">
        <h5>New dependency scan</h5>
    </div>
    <div class="row">
        <div class="col s12" style="margin-top: 1em;">
            <div class="col s12 depscan-help-card">
                <b>Help:</b> Paste here the link to your python / ruby code repository. Your repository must be publicly accessible.<br>This project only supports pip requirements files and gem files.
            </div>
        </div>
        <div class="col s12">
            <div class="depscan-card z-depth-1 col s12" style="margin-top: 1em; padding: 0;">
                <div class="col s12 depscan-card-title-wrapper">
                    <h5 class="depscan-card-title">Add a new repository</h5>
                </div>
                <div class="col s12">
                    <div class="col s12">
                        <form method="post" action=".">
                            {% csrf_token %}
                            <div class="input-field col s12">
                                <input id="ID" name="name" type="text" class="validate" style="margin-bottom: 1em;" required="true"/>
                                <label for="ID">Scan name</label>
                            </div>
                            <div class="input-field col s12">
                                <input id="ID" name="repo_link" type="text" class="validate" style="margin-bottom: 1em;" required="true"/>
                                <label for="ID">Git repository link</label>
                            </div>
                            <div class="col s12 center" style="margin: 1em 0">
                                <button type="submit" class="waves-effect waves-light btn depscan-btn">
                                    <i class="material-icons left">search</i>
                                    Start scanning
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}